package tests;// Generated by Selenium IDE

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class ContactCreationTests extends TestBase {
    private WebDriver driver;

    @BeforeEach
    public void setUp() {
        if (driver == null) {
            driver = new ChromeDriver();
            driver.get("http://localhost/addressbook/");
            driver.manage().window().setSize(new Dimension(1377, 937));
            driver.findElement(By.name("user")).sendKeys("admin");
            driver.findElement(By.name("pass")).sendKeys("secret");
            driver.findElement(By.xpath("//input[@value=\'Login\']")).click();
        }
    }

    @Test
    public void createContactsTests() {
        driver.findElement(By.linkText("add new")).click();
        driver.findElement(By.name("firstname")).sendKeys("first");
        driver.findElement(By.name("middlename")).sendKeys("middle");
        driver.findElement(By.name("lastname")).sendKeys("last");
        driver.findElement(By.name("nickname")).sendKeys("nick");
        driver.findElement(By.name("title")).sendKeys("title");
        driver.findElement(By.name("company")).sendKeys("company");
        driver.findElement(By.name("address")).sendKeys("adress");
        driver.findElement(By.name("home")).sendKeys("home");
        driver.findElement(By.name("mobile")).sendKeys("mobile");
        driver.findElement(By.name("work")).sendKeys("work");
        driver.findElement(By.name("fax")).sendKeys("fax");
        driver.findElement(By.name("email")).sendKeys("email");
        driver.findElement(By.name("email2")).sendKeys("email2");
        driver.findElement(By.name("email3")).sendKeys("email3");
        driver.findElement(By.name("homepage")).sendKeys("homepage");
        driver.findElement(By.name("address2")).sendKeys("adress2");
        driver.findElement(By.name("phone2")).sendKeys("home2");
        driver.findElement(By.name("notes")).sendKeys("notes");
        driver.findElement(By.xpath("(//input[@name=\'submit\'])[2]")).click();
        driver.findElement(By.linkText("home page")).click();
        driver.findElement(By.linkText("Logout")).click();
    }

    @Test
    public void createContactsTestsWithoutName() {
        driver.findElement(By.linkText("add new")).click();
        driver.findElement(By.name("firstname")).sendKeys("");
        driver.findElement(By.name("middlename")).sendKeys("");
        driver.findElement(By.name("lastname")).sendKeys("");
        driver.findElement(By.name("nickname")).sendKeys("");
        driver.findElement(By.name("title")).sendKeys("");
        driver.findElement(By.name("company")).sendKeys("");
        driver.findElement(By.name("address")).sendKeys("");
        driver.findElement(By.name("home")).sendKeys("");
        driver.findElement(By.name("mobile")).sendKeys("");
        driver.findElement(By.name("work")).sendKeys("");
        driver.findElement(By.name("fax")).sendKeys("");
        driver.findElement(By.name("email")).sendKeys("");
        driver.findElement(By.name("email2")).sendKeys("");
        driver.findElement(By.name("email3")).sendKeys("");
        driver.findElement(By.name("homepage")).sendKeys("");
        driver.findElement(By.name("address2")).sendKeys("");
        driver.findElement(By.name("phone2")).sendKeys("");
        driver.findElement(By.name("notes")).sendKeys("");
        driver.findElement(By.xpath("(//input[@name=\'submit\'])[2]")).click();
        driver.findElement(By.linkText("home page")).click();
        driver.findElement(By.linkText("Logout")).click();
    }

    @Test
    public void createContactsTestsWithSomeName() {
        driver.findElement(By.linkText("add new")).click();
        driver.findElement(By.name("firstname")).sendKeys("some name");
        driver.findElement(By.name("middlename")).sendKeys("");
        driver.findElement(By.name("lastname")).sendKeys("");
        driver.findElement(By.name("nickname")).sendKeys("");
        driver.findElement(By.name("title")).sendKeys("");
        driver.findElement(By.name("company")).sendKeys("");
        driver.findElement(By.name("address")).sendKeys("");
        driver.findElement(By.name("home")).sendKeys("");
        driver.findElement(By.name("mobile")).sendKeys("");
        driver.findElement(By.name("work")).sendKeys("");
        driver.findElement(By.name("fax")).sendKeys("");
        driver.findElement(By.name("email")).sendKeys("");
        driver.findElement(By.name("email2")).sendKeys("");
        driver.findElement(By.name("email3")).sendKeys("");
        driver.findElement(By.name("homepage")).sendKeys("");
        driver.findElement(By.name("address2")).sendKeys("");
        driver.findElement(By.name("phone2")).sendKeys("");
        driver.findElement(By.name("notes")).sendKeys("");
        driver.findElement(By.xpath("(//input[@name=\'submit\'])[2]")).click();
        driver.findElement(By.linkText("home page")).click();
        driver.findElement(By.linkText("Logout")).click();
    }
}