package tests;// Generated by Selenium IDE

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import tests.TestBase;


public class ContactRemoveTests extends TestBase {
    private WebDriver driver;

    @BeforeEach
    public void setUp() {
        if (driver == null) {
            driver = new ChromeDriver();
            driver.get("http://localhost/addressbook/");
            driver.manage().window().setSize(new Dimension(1377, 937));
            driver.findElement(By.name("user")).sendKeys("admin");
            driver.findElement(By.name("pass")).sendKeys("secret");
            driver.findElement(By.xpath("//input[@value=\'Login\']")).click();
        }
    }

    @Test
    public void contactRemoveTests() {

        driver.findElement(By.xpath("//table[@id=\'maintable\']/tbody/tr[2]/td[2]")).click();
        driver.findElement(By.name("selected[]")).click();
        driver.findElement(By.xpath("//input[@value=\'Delete\']")).click();
        //assertThat(driver.switchTo().alert().getText(), is("Delete 1 addresses?"));
        driver.switchTo().alert().accept();
        driver.findElement(By.linkText("Logout")).click();
        driver.findElement(By.name("pass")).sendKeys("secret");
    }
}
